name: StartTech Infrastructure Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: "Infrastructure & Backend"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # This runs your cleanup and creates the VPC/ECS/S3
      - name: Deploy Infrastructure
        run: |
          chmod +x scripts/deploy-infrastructure.sh
          ./scripts/deploy-infrastructure.sh

      # Using the NEW name we just created
      - name: Deploy Backend to ECS
        run: |
          chmod +x scripts/deployment-backend.sh
          ./scripts/deployment-backend.sh

  frontend:
    name: "Frontend Deployment"
    needs: terraform # Only deploy frontend if infra is ready
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: |
          chmod +x scripts/deploy-frontend.sh
          ./scripts/deploy-frontend.sh